services:
 
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui: {}
